name: Spring Boot CI

on:
  push:
    branches:
      - main  # Runs CI whenever you push to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'  # Change if you're using Java 21

    - name: Build and test with Maven
      run: mvn -B clean verify
